#!/usr/bin/env python3
"""
Tigerd Issue Triage Script
Fetches GitHub issues and uses Claude to categorize them into a wiki roadmap.
"""

import os
import json
import requests
import anthropic
from datetime import datetime

GITHUB_TOKEN = os.environ["GITHUB_TOKEN"]
ANTHROPIC_API_KEY = os.environ["ANTHROPIC_API_KEY"]
REPO = os.environ.get("REPO", "miiglu/tigerd")

HEADERS = {
    "Authorization": f"token {GITHUB_TOKEN}",
    "Accept": "application/vnd.github+json",
}

TIGERD_CATEGORIES = [
    "Bug - IDE/Editor",
    "Bug - Tigerd Agent",
    "Bug - Cloudflare/AI",
    "Bug - Backend/Auth",
    "Feature Request - IDE",
    "Feature Request - Agent",
    "Feature Request - Billing/Plans",
    "Feature Request - Onboarding",
    "Question/Support",
    "Documentation",
    "Other",
]


def fetch_issues():
    """Fetch all open issues from the Tigerd repo."""
    issues = []
    page = 1
    while True:
        url = f"https://api.github.com/repos/{REPO}/issues"
        params = {
            "state": "open",
            "per_page": 100,
            "page": page,
            "sort": "created",
            "direction": "desc",
        }
        resp = requests.get(url, headers=HEADERS, params=params)
        resp.raise_for_status()
        data = resp.json()
        if not data:
            break
        # Filter out pull requests
        issues += [i for i in data if "pull_request" not in i]
        page += 1
    return issues


def format_issues_for_claude(issues):
    """Format issues into a prompt-friendly string."""
    lines = []
    for issue in issues:
        lines.append(
            f"#{issue['number']} | {issue['title']} | Labels: {[l['name'] for l in issue.get('labels', [])]}"
        )
    return "\n".join(lines)


def triage_with_claude(issues_text):
    """Use Claude to categorize issues."""
    client = anthropic.Anthropic(api_key=ANTHROPIC_API_KEY)

    categories_list = "\n".join(f"- {c}" for c in TIGERD_CATEGORIES)

    prompt = f"""You are helping triage GitHub issues for Tigerd — an AI-powered IDE built on top of Void editor with an agentic AI system (tigerd-agent) powered by Cloudflare AI Gateway routing to Claude.

Here are the open issues:

{issues_text}

Please categorize each issue into one of these categories:
{categories_list}

Return a JSON object where each key is a category name and the value is a list of issue objects with "number" and "title" fields. Only include categories that have at least one issue. Example:
{{
  "Bug - IDE/Editor": [
    {{"number": 12, "title": "Editor crashes on large files"}}
  ],
  "Feature Request - Agent": [
    {{"number": 34, "title": "Add MCP tool support"}}
  ]
}}

Return ONLY valid JSON, no explanation or markdown."""

    message = client.messages.create(
        model="claude-sonnet-4-6",
        max_tokens=4096,
        messages=[{"role": "user", "content": prompt}],
    )

    return message.content[0].text


def generate_markdown(categorized, total_issues):
    """Generate the wiki markdown from categorized issues."""
    now = datetime.utcnow().strftime("%Y-%m-%d %H:%M UTC")

    lines = [
        "# Tigerd Issue Categories",
        "",
        f"> Auto-generated by Claude · Last updated: {now} · Total open issues: {total_issues}",
        "",
        "---",
        "",
    ]

    for category, issues in categorized.items():
        if not issues:
            continue
        lines.append(f"## {category} ({len(issues)})")
        lines.append("")
        for issue in issues:
            num = issue.get("number", "?")
            title = issue.get("title", "Untitled")
            lines.append(f"- [#{num} {title}](https://github.com/{REPO}/issues/{num})")
        lines.append("")

    lines += [
        "---",
        "",
        f"*Generated automatically every 6 hours using [Claude](https://anthropic.com) · [View all issues](https://github.com/{REPO}/issues)*",
    ]

    return "\n".join(lines)


def main():
    # Fetch issues
    issues = fetch_issues()
    if not issues:
        print("# Tigerd Issue Categories\n\nNo open issues found.")
        return

    # Format for Claude
    issues_text = format_issues_for_claude(issues)

    # Triage with Claude
    raw_json = triage_with_claude(issues_text)

    # Parse response
    try:
        categorized = json.loads(raw_json)
    except json.JSONDecodeError:
        # Try to extract JSON if Claude added any extra text
        import re
        match = re.search(r"\{.*\}", raw_json, re.DOTALL)
        if match:
            categorized = json.loads(match.group())
        else:
            print("# Tigerd Issue Categories\n\nError parsing Claude response.")
            return

    # Generate markdown
    markdown = generate_markdown(categorized, len(issues))
    print(markdown)


if __name__ == "__main__":
    main()
